name             'rb-hub-satellite'
maintainer       'Eneo Tecnología S.L.'
maintainer_email 'git@redborder.com'
license          'AGPL-3.0'
description      'Installs/Configures redborder-hub-satellite'
version          '2.0.0'
